# Generated by Django 4.0.4 on 2022-04-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='질문')),
                ('category', models.CharField(choices=[('0', 'normal'), ('1', 'account'), ('2', 'etc')], default='0', max_length=1)),
                ('comment', models.TextField(verbose_name='답변')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_at', models.DateTimeField(blank=True, null=True, verbose_name='최종수정일시')),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_modify_by', to=settings.AUTH_USER_MODEL, verbose_name='최종수정자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
