# Generated by Django 4.0.4 on 2022-05-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='질문')),
                ('category', models.CharField(choices=[('0', 'normal'), ('1', 'account'), ('2', 'etc')], default='0', max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
