# Generated by Django 4.0.4 on 2022-05-10 14:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_inquiry_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='전화번호'),
        ),
    ]
